# Generated by Django 2.1.4 on 2019-01-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.TextField(blank=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.TextField(blank=''),
        ),
    ]
